### ISSUE TITLE
chapter 3 - building functions 2b solution

### ISSUE THREAD

**Issue by totano** [johnchandlerburnham/hpfp#3]
book says 
-- Given
"Curry is awesome!" 
-- Return
"y"
return value is a string, so the solution should use take and drop, not !! operator
e.g. stringAt5 s = take 1 (drop 4 s)

**Comment by johnchandlerburnham** [comment]
Hi, thanks for the contribution and sorry for not responding to this until now.

I think your answer is perfectly valid, and in some ways better, but since these are my personal notes, I think I want to leave `(!! 4)` as is for a few reasons:

1. I don't really like slicing `Data.List`. It's a stack, not an array. `Data.Vector` is the slicey structure. I see the following definition floating around the internet sometimes:

```
slice :: Int -> Int -> [a] -> [a]
slice start end xs = take (end - start) $ drop start xs
```

I feel like this has unslice-like behavior, e.g. if `end < start`, `end > length xs`, `start < 0 || end < 0`.

2. At a more abstract level, `Char` is monomorphic to `[Char]` via `pure` and this becomes an isomorphism if we restrict the list to be of a single element. So looking back on it there's actually a kind of [univalent](https://ncatlab.org/nlab/show/univalence+axiom) subversiveness to `(!! 4)` as an answer which amuses me. Is `(!! 4) ~ (pure . (!! 4))`?

3. There are many places in this book where I didn't like the question and either didn't answer it or answered a slightly different question that I made up that I felt fit the chapter better. These were important learning moments for me, and I don't want to retroactively edit them out.

Anyway, thanks again for the issue and giving me the occasion to think/articulate all this!
